all:
	javac *.java -d out
test1:
	cd out && java JackCompiler ../../Seven
test2:
	cd out && java JackCompiler ../../ConvertToBin
test3:
	cd out && java JackCompiler ../../Square
test4:
	cd out && java JackCompiler ../../Average
test5:
	cd out && java JackCompiler ../../Pong
test6:
	cd out && java JackCompiler ../../ComplexArrays
	
clean:
	rm -rf out
