all:
	javac *.java -d out
test1:
	cd out && java JackAnalyzer ../../Square

test2:
	cd out && java JackAnalyzer ../../ExpressionLessSquare
test3:
	cd out && java JackAnalyzer ../../ArrayTest


clean:
	rm -rf out
